### PR TITLE
Fix language patch url

### PR DESCRIPTION
**Pull request by gsvr**

### CODE REVIEW

**Comment by gsvr** [comment]
@imsickofmaps Please review.

**Comment by imsickofmaps** [comment]
:+1:

**Comment by hodgestar** [comment]
@imsickofmaps @gsvr I assume this is still needed? The repo has moved on so we'll need to rework the PR a bit.

**Comment by imsickofmaps** [comment]
@hodgestar I would expect so yes. It's a trailing slash on POSTs issue.

**Comment by NicolaasDieBaas** [comment]
implemented elsewhere

**Pull request closed without merging**
